services:
  operator:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 12516
        P2P_UDP_PORT: 13516
    ports:
      - 12516:12516/tcp
      - 13516:13516/udp
  dkg:
    build:
      args:
        NETWORK: mainnet
        DKG_PORT: 14516
    ports:
      - "14516:14516"