services:
  operator:
    build:
      args:
        NETWORK: mainnet
        P2P_TCP_PORT: 12517
        P2P_UDP_PORT: 13517
    ports:
      - 12517:12517/tcp
      - 13517:13517/udp
  dkg:
    build:
      args:
        NETWORK: mainnet
        DKG_PORT: 14517
    ports:
      - "14517:14517"